@startuml

title protossConRecursosTest
Test->jugadorProtoss :incrementarMineral(100)
activate Test
activate jugadorProtoss
Test->jugadorProtoss :crearPilon()
Test->jugadorProtoss :crearZealot()
Test->jugadorProtoss :cantidadDeUnidades(ZEALOT)
jugadorProtoss->Test : cantidadDeZealots
Test->Test :assertEquals(cantidadDeZealots, 1)

@enduml