@startuml

class AlgoStar{
    -jugadores: Jugador
    -mapa: Mapa
    +AlgoStar(cantidadDeBases)
    +guardarMapa(unMapa)
    +pedirNombre(unNombre)
    +pedirColor(unColor)
    +pedirRaza(unaRaza)
    +validarJugador()
    +guardarJugador(unJugador)
    +iniciarPartida()
    +avanzarTurno()
}

note left: El metodo para validar al jugador se encarga de comparar\nel nombre de los jugadores, el color y la raza.

interface Jugador

class Mapa{
    -tamaño: int
    -areasDeTierra
    -areasEspaciales
    -ubicaciones: Ubicacion
    +Mapa(cantidadDeBases)
    +crearBase()
    +obtenerUbicacionBase()
}

AlgoStar --> Jugador
AlgoStar -> Mapa

@enduml
